<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.2" name="world_tileset" tilewidth="8" tileheight="8" tilecount="494" columns="26">
 <image source="Tiles-and-Enemies.png" width="208" height="152"/>
 <tile id="0" type="Ground"/>
 <tile id="1" type="Ground"/>
 <tile id="2" type="Ground"/>
 <tile id="26" type="Ground"/>
 <tile id="27" type="Ground"/>
 <tile id="28" type="Ground"/>
 <tile id="52" type="Ground"/>
 <tile id="53" type="Ground"/>
 <tile id="54" type="Ground"/>
 <tile id="55" type="Ground"/>
 <tile id="56" type="Ground"/>
 <tile id="57" type="Ground"/>
 <tile id="59" type="Ground"/>
 <tile id="60" type="Ground"/>
 <tile id="61" type="Moss"/>
 <tile id="62" type="Ground"/>
 <tile id="63" type="Sky"/>
 <tile id="64" type="Sky"/>
 <tile id="78" type="Ground"/>
 <tile id="80" type="Ground"/>
 <tile id="81" type="Ground"/>
 <tile id="82" type="Ground"/>
 <tile id="84" type="Ground"/>
 <tile id="85" type="Ground"/>
 <tile id="86" type="Ground"/>
 <tile id="87" type="Ground"/>
 <tile id="88" type="Ground"/>
 <tile id="89" type="Sky"/>
 <tile id="90" type="Sky"/>
 <tile id="107" type="Ground"/>
 <tile id="108" type="Ground"/>
 <tile id="111" type="Ground"/>
 <tile id="112" type="Ground"/>
 <tile id="113" type="Ground"/>
 <tile id="114" type="Ground"/>
 <tile id="115" type="Sky"/>
 <tile id="116" type="Sky"/>
 <tile id="130" type="Sky"/>
 <tile id="131" type="Ground"/>
 <tile id="132" type="Ground"/>
 <tile id="133" type="Ground"/>
 <tile id="134" type="Ground"/>
 <tile id="135" type="Ground"/>
 <tile id="137" type="Ground"/>
 <tile id="138" type="Ground"/>
 <tile id="139" type="Ground"/>
 <tile id="140" type="Ground"/>
 <tile id="141" type="Sky"/>
 <tile id="142" type="Sky"/>
 <tile id="156" type="Ground"/>
 <tile id="157" type="Ground"/>
 <tile id="158" type="Ground"/>
 <tile id="159" type="Ground"/>
 <tile id="160" type="Ground"/>
 <tile id="162" type="Ground"/>
 <tile id="163" type="Ground"/>
 <tile id="164" type="Ground"/>
 <tile id="165" type="Ground"/>
 <tile id="166" type="Ground"/>
 <tile id="167" type="Sky"/>
 <tile id="168" type="Sky"/>
 <tile id="185" type="Ground"/>
 <tile id="186" type="Ground"/>
 <tile id="189" type="Ground"/>
 <tile id="190" type="Ground"/>
 <tile id="191" type="Ground"/>
 <tile id="192" type="Ground"/>
 <tile id="193" type="Sky"/>
 <tile id="194" type="Sky"/>
 <tile id="219" type="Sky"/>
 <tile id="220" type="Sky"/>
 <tile id="245" type="Sky"/>
 <tile id="246" type="Sky"/>
 <tile id="271" type="Sky"/>
 <tile id="272" type="Sky"/>
 <tile id="294" type="Ground"/>
 <tile id="297" type="Sky"/>
 <tile id="298" type="Sky"/>
 <tile id="338" type="Sky"/>
 <tile id="339" type="Sky"/>
 <tile id="340" type="Sky"/>
 <tile id="341" type="Sky"/>
 <tile id="342" type="Sky"/>
 <tile id="343" type="Sky"/>
 <tile id="344" type="Sky"/>
 <tile id="345" type="Sky"/>
 <tile id="346" type="Sky"/>
 <tile id="347" type="Sky"/>
 <tile id="348" type="Sky"/>
 <tile id="349" type="Sky"/>
 <tile id="350" type="Sky"/>
 <tile id="364" type="Sky"/>
 <tile id="365" type="Sky"/>
 <tile id="366" type="Sky"/>
 <tile id="367" type="Sky"/>
 <tile id="368" type="Sky"/>
 <tile id="369" type="Sky"/>
 <tile id="370" type="Sky"/>
 <tile id="371" type="Sky"/>
 <tile id="372" type="Sky"/>
 <tile id="373" type="Sky"/>
 <tile id="374" type="Sky"/>
 <tile id="375" type="Sky"/>
 <tile id="376" type="Sky"/>
 <tile id="399" type="Ground"/>
 <tile id="400" type="Ground"/>
 <tile id="425" type="Ground"/>
 <tile id="426" type="Ground"/>
</tileset>
